name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [main]
    paths: [birdnet_analyzer/**, .github/workflows/ci.yml, tests/**, pyproject.toml]
  push:
    branches: [main]
    paths: [birdnet_analyzer/**, .github/workflows/ci.yml, tests/**, pyproject.toml]

concurrency:
  group: "${{ github.event.pull_request.number }}-${{ github.ref_name }}-${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  running-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
            python-version: ${{ matrix.python-version }}
            cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[all]
      - name: Run tests
        run: |
          python -m pip install pytest
          pytest

